### ISSUE TITLE
make a roslyn source code generator for this

### ISSUE THREAD

**Issue by ignatandrei** [mocklis/mocklis#18]
Please make a roslyn source code generator for this. It will help making the class partial

**Comment by eredmo** [comment]
Hi @ignatandrei

Yes - this request has come up before, and the key is how to give enough information to the source generator to do its job.

Currently a new mock class is built up from:
* a name
* one or more interfaces to implement (and a base class thought that is rarely used)
* some flags, such as strictness and how to mock methods that return by reference.

So this is the information we'd need to be able to provide regardless of approach.

As I see it we have two ways to go about it. The simpler one is to have a new assembly-level attribute that can be added to the source code and is read by the generator.

The more complex one is to add a new file type, with some sort of syntax to let the source code generator know what to generate. In this case we could extend this with some sort of wildcard: "create simple mock classes for all new interfaces in this or these namespaces". For it to be truly useful it would also need to provide intellisense, and syntax highlighting.

Then again - these must all be common problems for Roslyn source generator based solutions. Some research is definitely called for.

What do you think?

**Comment by ignatandrei** [comment]
Recognize the class to mock from an attribute

**Comment by ignatandrei** [comment]
like thios
[MockInterface]
public class Mockl

**Comment by eredmo** [comment]
There is now an alpha release (1.4.0-alpha.1) with support for this. Use the same attribute (MocklisClass) but make the class partial.

[MocklisClass]
public partial class TestMock : ITest;

(The alpha release also contains the ReturnTask step - which 'removes' the Task or ValueTask from the return value and wraps any value or exception that it receives from further downstream. For a method that returns a Task<double> you could do something like this: mockClass.TestMethod.ReturnTask().Return(5.0) instead of mockClass.TestMethod.Return(Task.FromResult(5.0)).)

**Comment by ignatandrei** [comment]
What is the package name from https://www.nuget.org/profiles/mocklis  ?

( I want to add to my curated list of Roslyn Source Code Generator, https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

**Comment by eredmo** [comment]
Mocklis is a meta-package that references both the generator (Mocklis.MockGenerator), and the support packages Mocklis.Core, which contains types necessary for the generated code, and Mocklis.BaseApi, which contains types useful for using the generated mocks.

So if you reference the Mocklis package from your solution, you get all you need. Note that you'll need the 1.4.0 alpha in order to get the source generator - all versions prior rely on an analyzer/code-fix approach.

**Comment by ignatandrei** [comment]
Unfortunately, it does not generate class . Please see the solution in the zip  attached below


[src.zip](https://github.com/mocklis/mocklis/files/13814144/src.zip)

( it cannot find the MocklisClassAttribute

**Comment by eredmo** [comment]
I think the problem was that one of your projects was named MockLis and Visual Studio couldn't therefore distinguish between that and the Mocklis NuGet package. I've renamed it to MockLisCode (although for completeness sake the name pun requires it to be one word - Mocklis without the uppercase L).

Once the project was renamed the namespace was correctly imported. I've updated the test as well. Find attached.
[src.zip](https://github.com/mocklis/mocklis/files/13817643/src.zip)

Hope that helps and don't hesitate if you have further questions.

**Comment by ignatandrei** [comment]
Yes, it works now. And thanks for the project. 

Now it is listed at https://ignatandrei.github.io/RSCG_Examples/v2/docs/mocklis

( If you want to make some changes, please let me know ( it is generated from <RSCG_Examples>\v2\rscg_examples\mocklis\description.json  )
